spring.application.name=live
server.port=8080
server.error.include-message=always
# Enable the web-based console
spring.h2.console.enabled=true
# The URL path to access it
spring.h2.console.path=/h2-console
# Allows you to see it from your browser
spring.h2.console.settings.web-allow-others=true
